version: '3.8'
services:
  ui:
    build:
      context: .
    ports:
    - '4200:4200'
    volumes:
    - .:/algamoney-ui
    - 'boxui:/node_modules'
    environment: 
      - API=app
    command: ng serve --host 0.0.0.0
    stdin_open: true
    networks:
      - algamoney-net
  boxui:
    image: busybox
    volumes:
      - /boxui
    networks:
      - algamoney-net

networks:
  algamoney-net:
    name: algamoney-net

volumes:
  boxui: